(deftheme solarized-dark-custom
  "Created 2013-10-08.")

(custom-theme-set-variables
 'solarized-dark-custom
 )

(custom-theme-set-faces
 'solarized-dark-custom
 '(cursor ((t (:background "chartreuse1" :foreground "#002b36"))))
 '(error ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(escape-glyph-face ((t (:foreground "#dc322f"))))
 '(fringe ((t (:foreground "#586e75" :background "#073642"))))
 '(linum ((t (:foreground "#586e75" :background "#073642"))))
 '(header-line ((t (:foreground "#839496" :background "#073642" :weight normal :slant normal :underline nil :inverse-video t))))
 '(highlight ((t (:background "#073642"))))
 '(hl-line ((t (:underline nil :background "#073642"))))
 '(isearch ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#cb4b16" :background "#002b36"))))
 '(isearch-fail ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#cb4b16" :background "#002b36"))))
 '(lazy-highlight ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#b58900" :background "#002b36"))))
 '(link ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#6c71c4"))))
 '(link-visited ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#d33682"))))
 '(menu ((t (:foreground "#839496" :background "#073642"))))
 '(minibuffer-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2aa198"))))
 '(mode-line ((t (:foreground "#93a1a1" :background "#073642" :weight normal :slant normal :underline nil :inverse-video t :box nil))))
 '(mode-line-inactive ((t (:foreground "#657b83" :background "#073642" :weight normal :slant normal :underline nil :inverse-video t :box nil))))
 '(region ((t (:foreground "#586e75" :background "#002b36" :weight normal :slant normal :underline nil :inverse-video t))))
 '(secondary-selection ((t (:background "#073642"))))
 '(shadow ((t (:foreground "#586e75"))))
 '(trailing-whitespace ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#dc322f"))))
 '(vertical-border ((t (:foreground "#839496"))))
 '(comint-highlight-prompt ((t (:foreground "#268bd2"))))
 '(compilation-info ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(compilation-warning ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#cb4b16"))))
 '(custom-button ((t (:foreground "#93a1a1" :background "#073642" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#93a1a1" :background "#073642" :inherit custom-button))))
 '(custom-button-pressed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#93a1a1" :background "#073642" :box (:line-width 2 :style pressed-button) :inherit custom-button-mouse))))
 '(custom-changed ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#268bd2" :background "#fdf6e3"))))
 '(custom-comment ((t (:foreground "#93a1a1" :background "#073642"))))
 '(custom-comment-tag ((t (:foreground "#93a1a1" :background "#073642"))))
 '(custom-documentation ((t (:inherit default))))
 '(custom-group-tag ((t (:foreground "#93a1a1"))))
 '(custom-group-tag-1 ((t ((:weight bold :slant normal :underline nil :inverse-video nil) :foreground "#93a1a1"))))
 '(custom-invalid ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#dc322f" :background "#002b36"))))
 '(custom-link ((t (:foreground "#6c71c4"))))
 '(custom-state ((t (:foreground "#859900"))))
 '(custom-variable-tag ((t (:foreground "#93a1a1"))))
 '(diff-added ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(diff-changed ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#b58900"))))
 '(diff-removed ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(diff-refine-change ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#268bd2" :background "#002b36"))))
 '(diff-file-header ((t (:background "#002b36"))))
 '(diff-header ((t (:foreground "#93a1a1" :background "#002b36"))))
 '(ido-only-match ((t (:foreground "#859900"))))
 '(ido-subdir ((t (:foreground "#268bd2"))))
 '(ido-first-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(emacs-wiki-bad-link-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#dc322f"))))
 '(emacs-wiki-link-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#268bd2"))))
 '(emacs-wiki-verbatim-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#657b83"))))
 '(eshell-ls-archive ((t (:foreground "#d33682"))))
 '(eshell-ls-backup ((t (:foreground "#b58900"))))
 '(eshell-ls-clutter ((t (:foreground "#cb4b16"))))
 '(eshell-ls-directory ((t (:foreground "#268bd2"))))
 '(eshell-ls-executable ((t (:foreground "#859900"))))
 '(eshell-ls-missing ((t (:foreground "#dc322f"))))
 '(eshell-ls-product ((t (:foreground "#b58900"))))
 '(eshell-ls-readonly ((t (:foreground "#93a1a1"))))
 '(eshell-ls-special ((t (:foreground "#6c71c4"))))
 '(eshell-ls-symlink ((t (:foreground "#2aa198"))))
 '(eshell-ls-unreadable ((t (:foreground "#657b83"))))
 '(eshell-prompt ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(font-lock-builtin-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(font-lock-comment-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#586e75"))))
 '(font-lock-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2aa198"))))
 '(font-lock-function-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(font-lock-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(font-lock-string-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2aa198"))))
 '(font-lock-type-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#b58900"))))
 '(font-lock-variable-name-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(font-lock-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(font-lock-doc-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#586e75"))))
 '(font-lock-doc-string-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#586e75"))))
 '(font-lock-color-constant-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(font-lock-comment-delimiter-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#586e75"))))
 '(font-lock-preprocessor-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#cb4b16"))))
 '(font-lock-reference-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2aa198"))))
 '(font-lock-negation-char-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(font-lock-other-type-face ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#cb4b16"))))
 '(font-lock-special-keyword-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(font-lock-exit-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(font-lock-other-emphasized-face ((t (:weight bold :underline nil :inverse-video nil :foreground "#6c71c4"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#b58900"))))
 '(info-xref ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#268bd2"))))
 '(info-xref-visited ((t (:foreground "#d33682" :inherit info-xref))))
 '(org-hide ((t (:foreground "#002b36"))))
 '(org-todo ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#002b36" :background "#dc322f"))))
 '(org-done ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(org-todo-kwd-face ((t (:foreground "#dc322f" :background "#002b36"))))
 '(org-done-kwd-face ((t (:foreground "#859900" :background "#002b36"))))
 '(org-project-kwd-face ((t (:foreground "#6c71c4" :background "#002b36"))))
 '(org-waiting-kwd-face ((t (:foreground "#cb4b16" :background "#002b36"))))
 '(org-someday-kwd-face ((t (:foreground "#268bd2" :background "#002b36"))))
 '(org-started-kwd-face ((t (:foreground "#b58900" :background "#002b36"))))
 '(org-cancelled-kwd-face ((t (:foreground "#859900" :background "#002b36"))))
 '(org-delegated-kwd-face ((t (:foreground "#2aa198" :background "#002b36"))))
 '(table-cell ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#839496" :background "#002b36"))))
 '(outline-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(outline-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2aa198"))))
 '(outline-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#b58900"))))
 '(outline-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(outline-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#839496"))))
 '(outline-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#586e75"))))
 '(outline-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#cb4b16"))))
 '(outline-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#6c71c4"))))
 '(speedbar-button-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#93a1a1"))))
 '(speedbar-directory-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#cb4b16"))))
 '(speedbar-file-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(speedbar-highlight-face ((t (:background "#073642"))))
 '(speedbar-selected-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#b58900"))))
 '(speedbar-separator-face ((t (:weight normal :slant normal :underline nil :inverse-video t))))
 '(speedbar-tag-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(show-paren-match ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2aa198" :background "#073642"))))
 '(show-paren-mismatch ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f" :background "#586e75"))))
 '(widget-field ((t (:foreground "#93a1a1" :background "#073642" :box (:line-width 1) :inherit default))))
 '(widget-single-line-field ((t (:inherit widget-field))))
 '(bm-fringe-face ((t (:background "#cb4b16" :foreground "#002b36"))))
 '(bm-fringe-persistent-face ((t (:background "#268bd2" :foreground "#002b36"))))
 '(flymake-errline ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#dc322f" :background "#002b36"))))
 '(flymake-warnline ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f" :background "#002b36"))))
 '(column-marker-1 ((t (:background "#586e75"))))
 '(column-marker-2 ((t (:background "#2aa198"))))
 '(column-marker-3 ((t (:background "#6c71c4"))))
 '(jabber-activity-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(jabber-activity-personal-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(jabber-chat-error ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(jabber-chat-prompt-foreign ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(jabber-chat-prompt-local ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(jabber-chat-prompt-system ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(jabber-chat-text-foreign ((t (:foreground "#93a1a1"))))
 '(jabber-chat-text-local ((t (:foreground "#839496"))))
 '(jabber-chat-rare-time-face ((t (:weight normal :slant normal :underline t :inverse-video nil :foreground "#859900"))))
 '(jabber-roster-user-away ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#859900"))))
 '(jabber-roster-user-chatty ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#cb4b16"))))
 '(jabber-roster-user-dnd ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(jabber-roster-user-error ((t (:weight light :slant italic :foreground "#dc322f"))))
 '(jabber-roster-user-offline ((t (:foreground "#586e75"))))
 '(jabber-roster-user-online ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(jabber-roster-user-xa ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#d33682"))))
 '(git-gutter:modified ((t (:foreground "#6c71c4"))))
 '(git-gutter:added ((t (:foreground "#859900"))))
 '(git-gutter:deleted ((t (:foreground "#dc322f"))))
 '(gnus-cite-1 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(gnus-cite-2 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2aa198"))))
 '(gnus-cite-3 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#b58900"))))
 '(gnus-cite-4 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(gnus-cite-5 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#cb4b16"))))
 '(gnus-cite-6 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#6c71c4"))))
 '(gnus-cite-7 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(gnus-cite-8 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#d33682"))))
 '(gnus-cite-9 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#657b83"))))
 '(gnus-cite-10 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#586e75"))))
 '(gnus-cite-11 ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#073642"))))
 '(gnus-group-mail-1 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#fdf6e3"))))
 '(gnus-group-mail-1-empty ((t (:foreground "#fdf6e3"))))
 '(gnus-group-mail-2 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#eee8d5"))))
 '(gnus-group-mail-2-empty ((t (:foreground "#eee8d5"))))
 '(gnus-group-mail-3 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#d33682"))))
 '(gnus-group-mail-3-empty ((t (:foreground "#d33682"))))
 '(gnus-group-mail-low ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#657b83"))))
 '(gnus-group-mail-low-empty ((t (:foreground "#657b83"))))
 '(gnus-group-news-1 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#93a1a1"))))
 '(gnus-group-news-1-empty ((t (:foreground "#93a1a1"))))
 '(gnus-group-news-2 ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(gnus-group-news-2-empty ((t (:foreground "#268bd2"))))
 '(gnus-group-news-low ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#6c71c4"))))
 '(gnus-group-news-low-empty ((t (:foreground "#6c71c4"))))
 '(gnus-emphasis-highlight-words ((t (:weight normal :slant normal :underline nil :inverse-video nil (:foreground "#b58900")))))
 '(gnus-header-content ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#586e75"))))
 '(gnus-header-from ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#657b83"))))
 '(gnus-header-name ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#586e75"))))
 '(gnus-header-newsgroups ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#073642"))))
 '(gnus-header-subject ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(gnus-server-agent ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#fdf6e3"))))
 '(gnus-server-closed ((t (:weight normal :slant italic :underline nil :inverse-video nil :foreground "#93a1a1"))))
 '(gnus-server-denied ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#eee8d5"))))
 '(gnus-server-offline ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(gnus-server-opened ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#2aa198"))))
 '(gnus-signature ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#586e75"))))
 '(gnus-splash ((t (:foreground "#eee8d5"))))
 '(gnus-summary-cancelled ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(gnus-summary-high-ancient ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-high-read ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-read))))
 '(gnus-summary-high-ticked ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-ticked))))
 '(gnus-summary-high-undownloaded ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-undownloaded))))
 '(gnus-summary-high-unread ((t (:weight bold :slant normal :underline nil :inverse-video nil :inherit gnus-summary-normal-unread))))
 '(gnus-summary-low-ancient ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-read ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-unread ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-unread))))
 '(gnus-summary-low-ticked ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-low-undownloaded ((t (:weight normal :slant italic :underline nil :inverse-video nil :inherit gnus-summary-normal-ancient))))
 '(gnus-summary-normal-ancient ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(gnus-summary-normal-read ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#586e75"))))
 '(gnus-summary-normal-ticked ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(gnus-summary-normal-undownloaded ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#eee8d5"))))
 '(gnus-summary-normal-unread ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(gnus-summary-selected ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#002b36" :background "#b58900"))))
 '(message-mml ((t (:foreground "#268bd2"))))
 '(message-cited-text ((t (:foreground "#eee8d5"))))
 '(message-separator ((t (:foreground "#fdf6e3"))))
 '(message-header-xheader ((t (:foreground "#6c71c4"))))
 '(message-header-name ((t (:foreground "#2aa198"))))
 '(message-header-other ((t (:foreground "#dc322f"))))
 '(message-header-newsgroups ((t (:weight bold :underline nil :inverse-video nil :foreground "#b58900"))))
 '(message-header-subject ((t (:foreground "#657b83"))))
 '(message-header-cc ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#859900"))))
 '(message-header-to ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#93a1a1"))))
 '(paren-face ((t (:foreground "#586e75"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#2aa198"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#dc322f"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#859900"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#cb4b16"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#d33682"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#839496"))))
 '(slime-error-face ((t (:weight normal :slant normal :underline nil :inverse-video t :foreground "#dc322f"))))
 '(slime-note-face ((t (:foreground "#b58900"))))
 '(slime-repl-inputted-output-face ((t (:foreground "#dc322f"))))
 '(slime-repl-output-mouseover-face ((t (:box (:color "#fdf6e3")))))
 '(slime-style-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#cb4b16"))))
 '(slime-warning-face ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(whitespace-empty ((t (:foreground "#dc322f"))))
 '(whitespace-hspace ((t (:foreground "#cb4b16"))))
 '(whitespace-indentation ((t (:foreground "#073642"))))
 '(whitespace-space ((t (:foreground "#073642"))))
 '(whitespace-space-after-tab ((t (:foreground "#2aa198"))))
 '(whitespace-space-before-tab ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f"))))
 '(whitespace-tab ((t (:foreground "#073642"))))
 '(whitespace-trailing ((t (:weight bold :slant normal :underline nil :inverse-video nil :foreground "#dc322f" :background "#073642"))))
 '(whitespace-highlight-face ((t (:foreground "#dc322f" :background "#268bd2"))))
 '(whitespace-line ((t (:foreground "#d33682" :background "#002b36"))))
 '(rcirc-my-nick ((t (:foreground "#268bd2"))))
 '(rcirc-nick-in-message ((t (:foreground "#cb4b16"))))
 '(rcirc-other-nick ((t (:foreground "#859900"))))
 '(rcirc-prompt ((t (:foreground "#b58900"))))
 '(rcirc-bright-nick ((t (:foreground "#d33682"))))
 '(rcirc-server ((t (:foreground "#93a1a1"))))
 '(rcirc-timestamp ((t (:foreground "#586e75"))))
 '(erc-input-face ((t (:foreground "#586e75"))))
 '(erc-keyword-face ((t (:weight bold :underline nil :inverse-video nil :foreground "#b58900"))))
 '(erc-my-nick-face ((t (:foreground "#268bd2"))))
 '(erc-nick-default-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#2aa198"))))
 '(erc-notice-face ((t (:weight normal :slant normal :underline nil :inverse-video nil :foreground "#268bd2"))))
 '(erc-timestamp-face ((t (:foreground "#586e75"))))
 '(font-latex-warning-face ((t (:foreground "#dc322f"))))
 '(font-latex-sectioning-5-face ((t (:foreground "#6c71c4"))))
 '(flyspell-incorrect ((t (:foreground "#dc322f"))))
 '(flyspell-duplicate ((t (:foreground "#b58900"))))
 '(term-color-black ((t (:foreground "#073642"))))
 '(term-color-red ((t (:foreground "#dc322f"))))
 '(term-color-green ((t (:foreground "#859900"))))
 '(term-color-yellow ((t (:foreground "#b58900"))))
 '(term-color-blue ((t (:foreground "#268bd2"))))
 '(term-color-magenta ((t (:foreground "#d33682"))))
 '(term-color-cyan ((t (:foreground "#2aa198"))))
 '(term-color-white ((t (:foreground "#657b83"))))
 '(default ((t (:foreground "#839496" :background "#002b36")))))

(provide-theme 'solarized-dark-custom)
